spring:
  datasource:
    name: dev
    url: jdbc:mysql://10.199.187.189/blog?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cmp.entity
  configuration:
    call-setters-on-nulls: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0



pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

env: dev
